name: widgetbook_example
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  widgetbook: ^3.14.3
  widgetbook_annotation: ^3.5.0
  flutter_bloc: ^9.1.1
  http: ^1.4.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  equatable: ^2.0.7
  bloc: ^9.0.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.6.0
  logger: ^2.6.0
  path_provider: ^2.1.5
  provider: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  widgetbook_generator: ^3.13.0
  build_runner: ^2.5.4
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto/Roboto-Thin.ttf
          weight: 100
        - asset: assets/fonts/Roboto/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto/Roboto-Black.ttf
          weight: 900






